services:
  network-deploy-service:
    networks:
      - smosky

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-config-eureka-server-config:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  microservice-eureka-config:
    extends:
      service: microservice-base-config
    depends_on:
      config-server:
        condition: service_healthy