services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  config-server:
    image: "loctran070699/config-server:latest"
    container_name: configserver-ms
    ports:
      - "8070:8070"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  boilerplate-server:
    image: "loctran070699/boilerplate-server:latest"
    container_name: boilerplate-server-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "boilerplate-server"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  blog-server:
    image: "loctran070699/blog-server:latest"
    container_name: blog-server-ms
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: "blog-server"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  smosky:
    driver: "bridge"